script for ironfish check
pavlobornia/testnet-tools-public pull request #16
Opened 2022-05-27 16:57 UTC by AlexBusko

2022-05-29 12:28 UTC, pavlobornia requested changes

2022-05-29 12:28 UTC, pavlobornia commented on ironfish/status.sh
> +
додай комент або Readme для чого цей скрипт. Не розумію, для чого робити рестарт сходу

2022-05-29 12:28 UTC, pavlobornia commented on ironfish/status.sh
> +service ironfishd restart
поміняй на systemctl

2022-05-29 12:28 UTC, pavlobornia commented on ironfish/status.sh
> +
сервіс встигає піднятись і засинкатись за 1 секунду?

2022-05-29 12:28 UTC, pavlobornia commented on ironfish/status.sh
> +
Погрупуй команди. Пробіли через кожен рядок м'яко кажучи дивно виглядають

2022-05-29 19:56 UTC, AlexBusko commented on ironfish/status.sh
> +
якщо не робити рестарт то виводу команди ironfish accounts:balance не дочекаєшся.

2022-05-29 19:56 UTC, AlexBusko commented on ironfish/status.sh
> +service ironfishd restart
++

2022-05-30 11:44 UTC, AlexBusko commented on ironfish/status.sh
> +
ні не встигає переставив на 15 сек

2022-05-31 18:44 UTC, pavlobornia requested changes

2022-05-31 18:44 UTC, pavlobornia commented on ironfish/deposit.sh
> +until (( ))
для мене простіше і зрозуміліше `while true`

2022-05-31 18:44 UTC, pavlobornia commented on ironfish/deposit.sh
> +# умова циклу пуста тому він буде виконуватись безкінечно ???
гугли for, while, until в bash

2022-05-31 18:44 UTC, pavlobornia commented on ironfish/deposit.sh
> +            # навіщо таке довге очікування після депозиту ???
вибери комфортне для тебе. Не бачу змісту робити спробу кожні 3 хвилини, якщо токени не встигають змайнитись.

2022-05-31 18:46 UTC, pavlobornia requested changes

2022-05-31 18:46 UTC, pavlobornia commented on ironfish/deposit.sh
> +# умова циклу пуста тому він буде виконуватись безкінечно ???
гугли for, while, until в bash

2022-05-31 18:46 UTC, pavlobornia commented on ironfish/README.md
> +wget -q -O ironfish_status.sh https://raw.githubusercontent.com/pavlobornia/testnet-tools-public/feat/ironfish/ironfish/status.sh && chmod +x ironfish_status.sh
FYI в мастері буде інший шлях

2022-06-01 10:28 UTC, merged