Feat/readme
pavlobornia/testnet-tools-public pull request #18
Opened 2022-06-15 09:52 UTC by AlexBusko

скрипт кайв наразі видалив так як в ньому нема потреби була задумка шо в нас буде купа нод і я буду іх ложити перепіднімати в різних пулах, зараз KYVE на паузі тому поки без нього

2022-06-15 13:57 UTC, pavlobornia requested changes

2022-06-15 13:57 UTC, pavlobornia commented on ironfish/README.md
>  . ironfish_status.sh
@AlexBusko для чого я ревюваю PR, якщо ти зауваження не виправляєш?

2022-06-15 13:57 UTC, pavlobornia commented on ironfish/README.md
>  . ./ironfish_deposit.sh
то саме, що за крапка?

2022-06-15 13:57 UTC, pavlobornia commented on ironfish/README.md
> +tmux attach -t session
чому не заранити все однією командою?
Якщо людина перший раз користується tmux, вона навіть не буде знати як звідти вийти

2022-06-16 09:19 UTC, pavlobornia commented on ironfish/status.sh
>  ironfish status
yarn --cwd ~/ironfish/ironfish-cli/ start

2022-06-16 10:54 UTC, AlexBusko commented on ironfish/README.md
>  . ironfish_status.sh
+

2022-06-16 10:54 UTC, AlexBusko commented on ironfish/README.md
>  . ./ironfish_deposit.sh
поправив

2022-06-16 10:55 UTC, AlexBusko commented on ironfish/README.md
> +tmux attach -t session
переписав

2022-06-16 10:55 UTC, AlexBusko commented on ironfish/status.sh
>  ironfish status
done

2022-06-16 12:53 UTC, AlexBusko commented
where is comment?

2022-06-16 12:54 UTC, pavlobornia requested changes

2022-06-16 12:54 UTC, pavlobornia commented on ironfish/README.md
> +CTRL + C
цею командою вбиваєш сесію

deattach - Ctrl + B , D

2022-06-16 15:26 UTC, pavlobornia approved these changes

2022-06-16 15:26 UTC, merged