ironfish command repair in status script
pavlobornia/testnet-tools-public pull request #22
Opened 2022-09-19 12:09 UTC by AlexBusko

2022-09-20 12:02 UTC, pavlobornia requested changes

2022-09-20 12:02 UTC, pavlobornia commented on ironfish/status.sh
> +/usr/bin/ironfish accounts:balance
наскільки памятаю, там була проблема з цею командою, тому використовували шлях через yarn. @AlexBusko ти перевіряв що працює?

2022-09-20 12:02 UTC, pavlobornia commented on ironfish/README.md
> +wget -q -O ironfish_status.sh https://raw.githubusercontent.com/pavlobornia/testnet-tools-public/feat/ironfish/ironfish/status.sh && chmod +x ironfish_status.sh
робочий скрипт завжди буде лежати в мастері, тому треба посилатись на нього. Гілка feat/ironfish може бути видалена, після мерджа PR

2022-09-20 12:02 UTC, pavlobornia commented on ironfish/README.md
> -wget -q -O ironfish_deposit.sh https://raw.githubusercontent.com/pavlobornia/testnet-tools-public/master/ironfish/deposit.sh && chmod +x ironfish_deposit.sh
те саме, див. комент вище

2022-09-21 09:52 UTC, AlexBusko commented on ironfish/status.sh
> +/usr/bin/ironfish accounts:balance
так, це якраз після обнови такі зміни папка ironfish-cli зникла і тепер всі команди з /usr/bin/ironfish

2022-09-21 12:24 UTC, AlexBusko commented on ironfish/README.md
> +wget -q -O ironfish_status.sh https://raw.githubusercontent.com/pavlobornia/testnet-tools-public/feat/ironfish/ironfish/status.sh && chmod +x ironfish_status.sh
поправив

2022-09-21 12:34 UTC, pavlobornia approved these changes

2022-09-26 09:44 UTC, merged